// Copyright 2022 Will Winder (@winder)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once


#ifdef OLED_ENABLE
#    define OLED_DISPLAY_128X64
#endif

#define SPLIT_TRANSPORT_MIRROR
#define SPLIT_LAYER_STATE_ENABLE
#define SPLIT_MODS_ENABLE
#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 80

#ifdef RGBLIGHT_ENABLE
    #define RGBLIGHT_DEFAULT_MODE RGBLIGHT_MODE_RAINBOW_SWIRL+2
#endif

#ifdef RGB_MATRIX_ENABLE
#   define RGB_MATRIX_LED_COUNT 62
#   define RGB_MATRIX_SPLIT { 31, 31 }

#   define RGB_MATRIX_HUE_STEP 8
#   define RGB_MATRIX_SAT_STEP 16
#   define RGB_MATRIX_VAL_STEP 16
#   define RGB_MATRIX_SPD_STEP 10

// EFFECTS
#   define ENABLE_RGB_MATRIX_ALPHAS_MODS
#   define ENABLE_RGB_MATRIX_BREATHING

// KEYPRESSES EFFECTS
#   define RGB_MATRIX_KEYPRESSES
#   define ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE
#   define ENABLE_RGB_MATRIX_SOLID_REACTIVE
#   define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS
#   define ENABLE_RGB_MATRIX_SOLID_MULTISPLASH
#endif
